### ISSUE TITLE
Duplicate Countries

### ISSUE THREAD

**Issue by Arlind-Prosperoware** [kinotto/geonames.js#12]
When using the api to get all the countries 
`  const countries = await geoNames.countryInfo({}) //get continents
`

I'm getting duplicate countries

**Comment by kinotto** [comment]
the rest api is this one,

http://api.geonames.org/countryInfoJSON?formatted=true&lang=en&username=${YOUR_USERNAME}&style=full

replace ${YOUR_USERNAME} with your username, you will get the json response. If something is wrong in the payload you should contact geonames directly, they have a dedicated forum here:
http://forum.geonames.org/

**Comment by Arlind-Prosperoware** [comment]
Hi @kinotto , The issue seems to be resolved now. There are no more duplicate countries.
Thanks.

**Comment by kinotto** [comment]
great @Arlind-Prosperoware :)

**Comment by Arlind-Prosperoware** [comment]
Hello @kinotto ,

When I'm using the example code to get all the countries this is the REST API that is being invoked:
`https://secure.geonames.org/countryInfoJSON?username=prosperoware&lang=en` and this API is returning duplicates.

The API that you mentioned is returning the correct format but its not the API thats being called by the code.

**Comment by kinotto** [comment]
Hi @Arlind-Prosperoware ,
are you using the commercial tier? did you pass a token in the config object? try to avoid passing the token and see if you still get duplicates.

Anyways if you get duplicates you might ask directly in the geonames forum probably they can better address the problem and probably solve it :)

**Comment by kinotto** [comment]
As i told you the payload of the response is not under my control, and i cannot filter the data in the library cause it wouldn't be the correct solution the purpose of this library is just to wrap their service into a js module.
When you say duplicates i don't know at which countries you're referring to because i cannot find them, but a part from that if there is a bug in the service it is correct to raise it in order to make them fix it :)
